"""initial schema

Revision ID: 9c471dfa40ef
Revises: 
Create Date: 2026-07-07 16:08:59.576681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c471dfa40ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.Enum('publication', 'scenario', 'edit', 'external', name='sourcetype'), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='approvalstatus'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('decision_by', sa.String(length=64), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_workspace_id'), 'approval_requests', ['workspace_id'], unique=False)
    op.create_index('ix_workspace_status', 'approval_requests', ['workspace_id', 'status'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('created', 'approved', 'rejected', 'cancelled', name='approvaleventtype'), nullable=False),
    sa.Column('actor_user_id', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_reviewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_user_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idempotency_keys')
    op.drop_table('approval_reviewers')
    op.drop_table('approval_events')
    op.drop_table('outbox_events')
    op.drop_index('ix_workspace_status', table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_workspace_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###

    bind = op.get_bind()
    sa.Enum(name='sourcetype').drop(bind, checkfirst=True)
    sa.Enum(name='approvalstatus').drop(bind, checkfirst=True)
    sa.Enum(name='approvaleventtype').drop(bind, checkfirst=True)
